FROM node:latest

RUN mkdir -p /usr/src/app

COPY command-service /usr/src/app/command-service
COPY message-utils /usr/src/app/message-utils
COPY resolve-bus-seneca /usr/src/app/resolve-bus-seneca
WORKDIR /usr/src/app/resolve-bus-seneca
RUN npm install
WORKDIR /usr/src/app/command-service
RUN npm install
RUN npm install -g node-inspector@0.7.5

EXPOSE 57575

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

