FROM node:latest

RUN mkdir -p /usr/src/app

COPY readmodel /usr/src/app/readmodel
COPY db /usr/src/app/db
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/db
RUN npm install
WORKDIR /usr/src/app/readmodel
RUN npm install

EXPOSE 9229

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

