FROM node:latest

RUN mkdir -p /usr/src/app/webapp

COPY webapp /usr/src/app/webapp
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/webapp
RUN npm install
RUN npm install -g node-inspector@0.7.5
RUN cd /usr/src/app/webapp/static && ../node_modules/.bin/bower --allow-root install

EXPOSE 8080 57575

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

