FROM node:latest

RUN mkdir -p /usr/src/app/testing

COPY testing /usr/src/app/testing
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/testing
RUN npm install

EXPOSE 3005

CMD ip address | grep global && node node_modules/nodemon/bin/nodemon index.js

