FROM node:latest

RUN mkdir -p /usr/src/app/validator

COPY validator /usr/src/app/validator
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/validator
RUN npm install
RUN npm install -g node-inspector@0.7.5

EXPOSE 3003 57575

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]
