FROM node:latest

RUN mkdir -p /usr/src/app/validator

COPY validator /usr/src/app/validator
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/validator
RUN npm install

EXPOSE 3003

CMD ip address | grep global && node node_modules/nodemon/bin/nodemon index.js

