version: '2'

services:
  web-proxy:
    image: sturm/cqrs-grid-demo/web-proxy
    volumes:
      - ./web-proxy:/usr/src/app/web-proxy
    ports:
      - "3000:3000"
    links:
      - query-service
      - command-service
      - validator
      - testing
      
  query-service:
    image: sturm/cqrs-grid-demo/query-service
    volumes:
      - ./query-service:/usr/src/app/query-service
      - ./db:/usr/src/app/db
    ports:
      - "3001:3001"
    links:
      - mongo

  command-service:
    image: sturm/cqrs-grid-demo/command-service
    volumes:
      - ./command-service:/usr/src/app/command-service
      - ./db:/usr/src/app/db
    ports:
      - "3002:3002"
    links:
      - mongo
      - validator

  validator:
    image: sturm/cqrs-grid-demo/validator
    volumes:
      - ./validator:/usr/src/app/validator
    ports:
      - "3003:3003"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  webapp:
    image: sturm/cqrs-grid-demo/webapp
    volumes:
      - ./webapp:/usr/src/app/webapp
    ports:
      - "8080:8080"

  testing:
    image: sturm/cqrs-grid-demo/testing
    volumes:
      - ./testing:/usr/src/app/testing
    ports:
      - "3005:3005"
    links:
      - command-service
