version: '2'

services:
  web-proxy:
    image: sturm/cqrs-grid-demo/web-proxy
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    links:
      - rabbitmq
      
  query-service:
    image: sturm/cqrs-grid-demo/query-service
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - rabbitmq
      - mongo

  command-service:
    image: sturm/cqrs-grid-demo/command-service
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - rabbitmq
      - mongo

  readmodel:
    image: sturm/cqrs-grid-demo/readmodel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - rabbitmq
      - mongo

  query-change-detector:
    image: sturm/cqrs-grid-demo/query-change-detector
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    links:
      - rabbitmq

  validator:
    image: sturm/cqrs-grid-demo/validator
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    links:
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  webapp:
    image: sturm/cqrs-grid-demo/webapp
    ports:
      - "8080:8080"

  testing:
    image: sturm/cqrs-grid-demo/testing
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    links:
      - rabbitmq
