FROM node:latest

RUN mkdir -p /usr/src/app

COPY testing /usr/src/app/testing
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/testing
RUN npm install

EXPOSE 9229

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

