FROM node:latest

RUN mkdir -p /usr/src/app/query-service
RUN mkdir -p /usr/src/app/db

COPY query-service /usr/src/app/query-service
COPY db /usr/src/app/db
WORKDIR /usr/src/app/db
RUN npm install
WORKDIR /usr/src/app/query-service
RUN npm install

EXPOSE 3001

CMD ip address | grep global && node node_modules/nodemon/bin/nodemon index.js

