FROM node:latest

RUN mkdir -p /usr/src/app/webapp

COPY webapp /usr/src/app/webapp
WORKDIR /usr/src/app/webapp
RUN npm install
RUN cd /usr/src/app/webapp/static && ../node_modules/.bin/bower --allow-root install

EXPOSE 8080

CMD ip address | grep global && node node_modules/nodemon/bin/nodemon index.js

