FROM node:latest

RUN mkdir -p /usr/src/app/web-proxy

COPY web-proxy /usr/src/app/web-proxy
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/web-proxy
RUN npm install

EXPOSE 3000

CMD ip address | grep global && node node_modules/nodemon/bin/nodemon index.js

