version: '2'

services:
  web-proxy:
    image: sturm/cqrs-grid-demo/knockout-frontend/web-proxy
    ports:
      - "3000:3000"
    links:
      - query-service
      - command-service
      - validator
      - testing
      
  query-service:
    image: sturm/cqrs-grid-demo/knockout-frontend/query-service
    ports:
      - "3001:3001"
    links:
      - mongo

  command-service:
    image: sturm/cqrs-grid-demo/knockout-frontend/command-service
    ports:
      - "3002:3002"
    links:
      - mongo
      - validator

  validator:
    image: sturm/cqrs-grid-demo/knockout-frontend/validator
    ports:
      - "3003:3003"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  webapp:
    image: sturm/cqrs-grid-demo/knockout-frontend/webapp
    ports:
      - "8080:8080"

  testing:
    image: sturm/cqrs-grid-demo/knockout-frontend/testing
    ports:
      - "3005:3005"
    links:
      - command-service
