FROM node:latest

RUN mkdir -p /usr/src/app

COPY query-change-detector /usr/src/app/query-change-detector
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/query-change-detector
RUN npm install

EXPOSE 9229

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

