FROM node:latest

RUN mkdir -p /usr/src/app/query-service
RUN mkdir -p /usr/src/app/db

COPY query-service /usr/src/app/query-service
COPY db /usr/src/app/db
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/db
RUN npm install
WORKDIR /usr/src/app/query-service
RUN npm install

EXPOSE 3001 9229

RUN chmod 755 start-service.sh
CMD [ "./start-service.sh" ]

