FROM node:latest

RUN mkdir -p /usr/src/app/testing

COPY testing /usr/src/app/testing
COPY message-utils /usr/src/app/message-utils
WORKDIR /usr/src/app/testing
RUN npm install
RUN npm install -g node-inspector@0.7.5

EXPOSE 3005 57575

CMD bash start-service.sh
