{
    "script": [
        "cd $project_path",
        "make stop-run-without-docker",
        "EXCLUDE=QRYCHANGES make run-without-docker",
        "cd query-change-detector",
        "RABBITMQ_HOST=localhost node --harmony --nocrankshaft --nolazy --debug-brk=15454 index.js"
        ],
    "info" : "Starting demo, debugging query-change-detector service",
    "debugger": "v8",
    "debugport": 15454
}
